### PR TITLE
Initial commit to generate discussion

### PR DESCRIPTION
**Pull request by laserson**

### CODE REVIEW

**Comment by fnothaft** [comment]
LGTM; shall I merge?

**Comment by laserson** [comment]
Sure, though unless we want to discuss more what the schema should look like.

**Comment by fnothaft** [comment]
> Sure, though unless we want to discuss more what the schema should look like.

We can probably just evolve that over time, nyet?

**Comment by laserson** [comment]
k, merge away :)

**Comment by fnothaft** [comment]
Merged! Thanks @laserson!

**Pull request merged**
