### PR TITLE
[EGGO-18] WIP: Setup config files

### PR DESCRIPTION
**Pull request by laserson**
@tomwhite, could you check this out.  I want to get your opinion before I keep going in this direction.  I haven't tested any of it yet, so there are for-sure many random bugs to clean up.

### CODE REVIEW

**Comment by laserson** [comment]
Mainly, I add a config file for eggo and try to get as many options from there as possible.  There is still opportunity for quite a bit more.  Now, the user should generally only need to specify an `EGGO_CONFIG` variable pointing to their configuration.  Hopefully this'll make it easy to keep test profiles as well, for running locally and against HDFS and S3.

**Comment by laserson** [comment]
Ok, this is quite a large set of changes.  Apologies @tomwhite.  Also note to use the `eggo` command instead of `fab`. And you must also run a `deploy_eggo_config` command in there as well.  This needs serious cleanup, but should now be able to be broken down into digestible tasks.  CI is definitely needed...

**Comment by tomwhite** [comment]
Sorry I haven't had time to look at this. We should probably test changes before merging substantial updates like this. +1 to the direction though.

Nit: we could default EGGO_HOME and EGGO_CONFIG quite easily relative to bin/eggo.

**Comment by laserson** [comment]
Yeah, I agree, but figured I'd let this one go bc eggo is still rather unstable anyway.  Also, I was (basically) able to get the test-genotypes pipeline running with all these changes.

**Comment by tomwhite** [comment]
That's good to hear. We do need a functional test that we can run under CI (https://github.com/bigdatagenomics/eggo/issues/46) - I'll see if I can tackle it next week. 

This change also means the outstanding PRs (https://github.com/bigdatagenomics/eggo/pull/52, https://github.com/bigdatagenomics/eggo/pull/38) need to be essentially re-written :(

**Pull request merged**
