### PR TITLE
[EGGO-6] Update S3 bucket name

### LINKED ISSUE #6: Fix S3 bucket name

### PR DESCRIPTION
**Pull request by laserson**
Fixes #6.

### CODE REVIEW

**Comment by andypetrella** [comment]
cool!
Are these s3 supposed to be public, opened? I tried to list the content but got a 403.

Also, I'm wondering in which region the data are? Because, if it's okay, we could add also some references to `http://med-at-scale.s3.amazonaws.com/` where the `1kg` have been converted to ADAM as well, but located "here" in Europe.
WDYT? Would it be appreciated if we create a PR with these additions?

thanks a lot

**Comment by fnothaft** [comment]
> Are these s3 supposed to be public, opened? I tried to list the content but got a 403.

I think @laserson is trying to work out the permissions troubles; we should have this up and rolling soon.

> Also, I'm wondering in which region the data are? Because, if it's okay, we could add also some references to http://med-at-scale.s3.amazonaws.com/ where the 1kg have been converted to ADAM as well, but located "here" in Europe.
> WDYT? Would it be appreciated if we create a PR with these additions?

+1, I think that mirroring data would be great! The NA12878 pedigree data is actually in the UK, so I was going to start processing it on AWS there, and then move it over to the US (I don't know precisely where s3://bdg-eggo is, but I know it is in the US and would guess that it is US-east). @laserson thoughts?

**Comment by laserson** [comment]
+1 to mirroring as well.

I set up the bucket to be in US Standard (I'm guessing US-east), but I could presumably change that if people think it'd be more convenient elsewhere.

**Comment by andypetrella** [comment]
Yeah S3 permissions _sigh_

I guess where it is in US is not really an issue, like where it'd be in EU.
We could also discuss how we (with @xtordoir) could transition the conversion we've done to a `bdg-eggo-eu`.
So it'd remove the burden to do it yourself (or copy from US to EU which is painful ^^)

**Pull request merged**
